version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: teine-postgres
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: ownerpass
      POSTGRES_DB: teine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
